### ISSUE TITLE
ValueError: attempted relative import beyond top-level package

### ISSUE THREAD

**Issue by kovalewvladimir** [StoicPerlman/falcon-openapi#8]
This error occurs when:

```
test\
  api\
    controller.py
  model\
    model.py
  app.py
  api.yml
```

api.yaml
```
paths:
  /controller:
    get:
      summary: summary
      operationId: api.controller.controller1.on_get
```

app.py
```
import falcon
from falcon_openapi import OpenApiRouter

app = falcon.API(
    router=OpenApiRouter(file_path='api.yml'),
)
```

model\ model.py
```
class model1:
    pass
```

api\controller.py
```
from ..model.model import model1

class controller1(object):
    def on_get(self, req, resp):
        resp.body = 'test'
```

Traceback
```
Traceback (most recent call last):
  ...
  ...
  ...
  File "/test/api/controller.py", line 1, in <module>
	from ..model.model import model1
  ValueError: attempted relative import beyond top-level package
```
